apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 7.3.8
    chart: grafana
    helm:
      values: |-
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://vmsingle-victoria-metrics-vm.vm2.svc:8429/prometheus
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              access: proxy
              url: http://loki-gateway.loki-stack.svc.cluster.local/
              jsonData:
                timeout: 60
                maxLines: 1000
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
